TCS_NAME :=

TCS_SRC :=
TCS_INCS :=
TCS_REQUIRED_MODULES :=
TCS_CFLAGS :=

TCS_SHARED_LIBS_ANDROID_ONLY :=
TCS_SHARED_LIBS_HOST_ONLY :=
TCS_SHARED_LIBS :=

TCS_STATIC_LIBS_ANDROID_ONLY :=
TCS_STATIC_LIBS_HOST_ONLY :=
TCS_STATIC_LIBS :=

TCS_TARGET :=
TCS_DISABLE_HOST_TARGET :=
TCS_DISABLE_ANDROID_TARGET :=

TCS_LANG :=

TCS_COPY_HEADERS :=
TCS_COPY_HEADERS_TO :=
TCS_EXPORT_C_INCLUDE_DIRS :=
